model_path: "../models/ours"
results_dir: "../results/faust_intra_pca/"
intra_results_dir: "../results/faust_intra_pca/"
inter_results_dir: "../results/faust_inter_pca/"
faust_mode: "inter"
training:
  batch_size: 16 
  lr: 1e-3
  epochs: 100 
  device_ids: [0,1]
  data_device: 0
triangle_feature_dim: 128 
scan_feature_dim: 128 
local_feature_dim: 128 
pca_set: "../data/pipeline_data_ours/pca_set/"
njf_set: "../data/common/njf_set/"
njf_set_scans: "../data/common/njf_set_scans/"
njf_train_dir: "../data/pipeline_data_faust_intra/pair_maps/"
growth_set_src: "../data/caesar_scans_obj"
growth_set_rounds: "../data/pipeline_data_ours/growth_set/"
test_set: "../data/common/test_set/"
test_set_scans: "../data/common/test_set_scans/"
num_rounds: 72 
start_round: 71 
logdir: "../logs/faust_intra_eval/"
intra_logdir: "../logs/faust_intra_eval/"
inter_logdir: "../logs/faust_inter_eval/"
fresh: True
test: False 