model_path: "../models/ours_flame"
njf_model_path: "../models/ours"
results_dir: "../results_v4/ours_flame/"
training:
  batch_size: 16 
  lr: 1e-3
  epochs: 100 
  device_ids: [0,1]
  data_device: 0
triangle_feature_dim: 128 
scan_feature_dim: 128 
local_feature_dim: 128 
pca_set: "../data/pipeline_data_ours_flame/pca_set/"
njf_set: "../data/common/njf_set/"
njf_set_scans: "../data/scans/"
njf_train_dir: "../data/pipeline_data_ours_flame/pair_maps/"
growth_set_src: "../data/scans"
growth_set_rounds: "../data/pipeline_data_ours_flame/growth_set/"
test_set: "../data/common/test_set_flame/"
test_set_scans: "../data/common/test_set_scans_flame/"
num_rounds: 3 
start_round: 2 
k: 20
njf_start_round: 77
logdir: "../logs/flame/"
fresh: True
test: False 
