model_path: "../models/ours_mano"
njf_model_path: "../models/ours"
results_dir: "../results/ours_mano_r0/"
training:
  batch_size: 16 
  lr: 1e-3
  epochs: 100 
  device_ids: [0,1]
  data_device: 0
triangle_feature_dim: 128 
scan_feature_dim: 128 
local_feature_dim: 128 
pca_set: "../data/pipeline_data_ours_mano/pca_set/"
njf_set: "../data/common/njf_set/"
njf_set_scans: "../data/mano_some_scans/"
njf_train_dir: "../data/pipeline_data_ours_mano/pair_maps/"
growth_set_src: "../data/mano_some_scans"
growth_set_rounds: "../data/pipeline_data_ours_mano/growth_set/"
test_set: "../data/mano_some_regs/"
test_set_scans: "../data/mano_some_scans/"
num_rounds: 1
start_round: 0
k: 20
njf_start_round: 77
logdir: "../logs/mano/"
fresh: True
test: False 
