model_path: "../models/ours_ae"
results_dir: "../results/ours_ae/"
training:
  batch_size: 16 
  lr: 1e-3
  epochs: 100 
  device_ids: [0,1]
  data_device: 0
triangle_feature_dim: 128 
scan_feature_dim: 128 
local_feature_dim: 128 
pca_set: "../data/pipeline_data_ae/pca_set/"
njf_set: "../data/common/njf_set/"
njf_set_scans: "../data/common/njf_set_scans/"
njf_train_dir: "../data/pipeline_data_ae/pair_maps/"
growth_set_src: "../data/caesar_scans_obj"
growth_set_rounds: "../data/pipeline_data_ae/growth_set/"
test_set: "../data/common/test_set_ae/"
test_set_scans: "../data/common/test_set_scans_ae/"
num_rounds: 100
start_round: 0 
logdir: "../logs/ae/"
fresh: True
test: False 
